language: node_js
sudo: false
node_js:
  - 0.1
  - 0.12
  - 4
env:
  global:
    - EMAIL_USERNAME: "hello@benedfit.com"
    - GITHUB_REPO: "benedfit/avalancheuk"
    - secure: dinCMQyvgK/OqVtykRjUWLpnIsXUznqQjNT+NIxsmAcGo+RnpmQ0x6ewEkUExmwUQDp6nMMiFgCI2esG+B31/8HvdqcdJio5ZUpB69SETA2GXUEe2E+dfmyj3O7aJSBTVJE9rHEfOoTJh6MbJQoURsLEhXgAwno5N3vZEvLBKYxHW6BlQwPjL+iKBnxPUyQndSwFaATsTEfxURhwOXNmrrEplOgw2Uv55QrLXP/185ZvfCsilgnzgvwTBe0BfOrbfHfnMxikro4jzHFvAYFGYPpkP6yz8KpvLSrCb4/JKKAeLhMCpnMbQjmrAoqKXhcUBq0xgAWw1kKMFme9BsS5I2hdkirMWBREJE4c7SPiM6S5lvLh93uggg6EvtOaIhAjWKvM4uJt5WbVLZTIoCKO+iniIWyV2q8B16n2gK0LzdJ17jzODovCKGtdXt2C5gQUYtLIzd4L8uj5M5mMFzKa3hR9FiYV/ILEOjTwv5Gb3LN9BeqKINzXYhwWKn537PalOm0yZoNauPR6tL8+MOBHDqFUFMtP9ttp9VXJJsSo6j1BePo1e1tnSaR266CeRkNYXL+dHa2xL9bfxaV2QoZsOA07Ux8faBj5nIKav/PHGRsJ53EB5Xcr98MpSRv3qV1x+L+AZ1zVR7HGqTIb4+qs4J3p1D6QGUne7hWCzTjOWEY=
    - secure: EILcIsoDEBA+XPaiaqkvO69tAxbFqs6die506WL0+NJea4DrliIXYJQzqIO9awJoG0hkOCQL9/tc9HbFRTi0nNiCtBbS26D2C96ZKjPOWRiH2yTemVmdm6KY2coBh+QFH1QjeqRILLRDG/6YSRqZWG8pXeWBnSlAz2DmPWvo470IHJO+nT35AGOYXmh5IQZUVLt22tS+OLLXrmbVMOVUL2/WigkrCIMhlfCpv2fsC8iRwnPF/unW/kjLQp/dgJSp9kfHatzfeotfudaAPKXnbH9NeYH3OZxCBaok8G4vSP8Mqub52Fqw1I7NSCoOmI5hCz1PAugBNzd+xj+IuIKZ1IIAQ2iecHQnJRVQjPVlMkZyJy2UMkVfHzd8yJ80cciGhDZTSr5vl2eqzRGSmTVslXqbR645boGRPcBubaCms96r3S/LRrpr5PUOpJl+qy62M/lodWOFYlslkQiYBU3k3QYuOeuvdJWxhxjXbE2NJTxq1NGMk1t0v4RcxP3x4TqtS16Is+d6dTdztQGxRN+hRCiOh8xqt8FpM60YJ4msi86d83aSnoKTK1rxys9xnAvl842emRmzik56IaQypRUv3XP0sVlwmFYBPwVtPiOcbKKMN7PDFGssAWx2UkAduocTH3MMXvu+NwZQ0U49+Sjiqms+v9wwxOrYmHa5FNa3vOM=
after_success:
  - npm run build
  - npm run deploy
notifications:
  email:
    on_success: never
